server:
  port: 8017
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: websocket-chat
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
#    show-sql: true
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    #    prefix: /static/
    prefix: classpath:/
    cache: false
  web:
    resources:
      static-locations:  classpath:/static/
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:super-os}:3306/${MYSQL_DB:movie}?useSSL=false&useUnicode=true&character_set_server=utf8mb4
    username: ${MYSQL_USERNAME:movie}
    password: ${MYSQL_PASSWORD:5diXYxcYL7H4LbRN}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 28800
      login-timeout: 5
      max-lifetime: 28800
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
      keepaliveTime: 28800
    dbcp2:
      test-on-borrow: true
      validation-query: Select 1
  redis:
    host: ${REDIS_HOST:super-os}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DB:0}
    password: ${REDIS_PASSWORD:2pmnpw47}
