server:
  port: 8017
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: websocket-chat
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/static/
    mode: LEGACYHTML5
  web:
    resources:
      static-locations:  classpath:/static/
  datasource:
    url: jdbc:mysql://api2.telebott.com:3306/movie?useSSL=false&useUnicode=true&character_set_server=utf8mb4
    username: movie
    password: 5diXYxcYL7H4LbRN
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 28800
      login-timeout: 5
      max-lifetime: 28800
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
      keepaliveTime: 28800
    dbcp2:
      test-on-borrow: true
      validation-query: Select 1
  redis:
    #    host: 119.8.56.223
    host: 127.0.0.1
    port: 6379
    database: 0
#    password: 2pmnpw47@